version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: notesdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_USER: root
      DB_PASS: yourpassword
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: notesdb
      JWT_SECRET: your_jwt_secret
    entrypoint: ["sh", "./entrypoint.sh"]
    command: ["./main", "-port", "3000"]

volumes:
  db_data:
